---
- name: Update Windows Host
  hosts: all
  tasks:
    - name: Install all available Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - DefinitionUpdates
        reboot: yes
      register: update_result

    - name: Reboot the server if required
      win_reboot:
        reboot_timeout: 3600
      when: update_result.reboot_required
