---
- name: Enable Active Directory Users and Computers Snap-in
  hosts: windows
  tasks:
    - name: "Ensure the 'RSAT: Active Directory Domain Services and Lightweight Directory Tools' feature is installed"
      win_feature:
        name: RSAT-AD-Tools
        state: present
        include_management_tools: yes
      register: rsat_installation

    - name: Reboot the server if required
      win_reboot:
        reboot_timeout: 3600
      when: rsat_installation.reboot_required
