---
- name: Check and Install Windows Updates
  hosts: all
  tasks:
    - name: Check for available Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: searched
      register: update_check

    - name: Install available Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      when: update_check.updates.count > 0
      register: update_result

    - name: Reboot the server if required
      win_reboot:
        reboot_timeout: 3600
      when: update_result.reboot_required
