---
- name: Update Windows Host
  hosts: windows
  tasks:
    - name: Install all available Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - DefinitionUpdates
        reboot: yes

    - name: Reboot the server if required
      win_reboot:
        reboot_timeout: 3600
      when: reboot_required.result == true
